version: '3'

services:
   seafile:
      build: docker/.
      container_name: seafile
      restart: unless-stopped
      networks:
         - seafile_proxy
      volumes:
         - ./data:/shared
      environment:
         SEAFILE_SERVER_IP: "www.example.com"
         SEAHUB_ADMIN_EMAIL: "admin@example.com"
         SEAHUB_ADMIN_PWD: "password"

   nginx:
      image: nginx
      container_name: seafile_nginx
      restart: unless-stopped
      depends_on:
         - seafile
      networks:
         - seafile_proxy
      links:
         - seafile
      ports:
         - "80:80"
         - "443:443"
      volumes:
         - ./config/seafile.nginx.conf:/etc/nginx/conf.d/seafile.nginx.conf:ro

networks:
   seafile_proxy:
